/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../config/wrangler-types.env --include-runtime=false --strict-vars=false` (hash: a81d9fae8225498dadb637f50a17437b)
interface __BaseEnv_Env {
  PHOTOS: R2Bucket;
  DB: D1Database;
  ALLOWED_ORIGINS: string;
  CHAT: Fetcher /* 0xnullai-chat */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'ALLOWED_ORIGINS'>> {}
}
