/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../config/wrangler-types.env --include-runtime=false --strict-vars=false` (hash: 1afbfad31f45c62fb347781b7dd198a7)
interface __BaseEnv_Env {
  PHOTOS: R2Bucket;
  DB: D1Database;
  EMAIL: SendEmail;
  ALLOWED_ORIGINS: string;
  IP_PEPPER: string;
  DM_TICKET_SECRET: string;
  CHAT: Fetcher /* 0xnullai-chat */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'ALLOWED_ORIGINS' | 'IP_PEPPER' | 'DM_TICKET_SECRET'>
  > {}
}
