/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../config/wrangler-types.env --include-runtime=false --strict-vars=false` (hash: b37e0ee023d868fca3df7a39e5d9a2b1)
interface __BaseEnv_Env {
  DB: D1Database;
  MARKET_IP_PEPPER: string;
  AUTH: Service /* entrypoint AuthOwnershipService from 0xnullai-auth */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/worker/index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'MARKET_IP_PEPPER'>> {}
}
