/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../config/wrangler-types.env --include-runtime=false --strict-vars=false` (hash: 7345b6981c30eaa78585a8182aac663a)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	AUTH: Service /* entrypoint AuthOwnershipService from 0xnullai-auth */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
