/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../config/wrangler-types.env --include-runtime=false --strict-vars=false` (hash: 55bcbe53729280e10438582cc07eb78c)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
