/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../config/wrangler-types.env --include-runtime=false --strict-vars=false` (hash: 24ea931b94073169051c78b528bf3cce)
interface __BaseEnv_Env {
  MEDIA: R2Bucket;
  DM_TICKET_SECRET: string;
  ROOM: DurableObjectNamespace<import('./worker/index').RoomDO>;
  LOBBY: DurableObjectNamespace<import('./worker/index').LobbyDO>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index');
    durableNamespaces: 'RoomDO' | 'LobbyDO';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'DM_TICKET_SECRET'>> {}
}
