/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../config/wrangler-types.env --include-runtime=false --strict-vars=false` (hash: 8b106aec0fab113c796563cc159d7b89)
interface __BaseEnv_Env {
  MEDIA: R2Bucket;
  ASSETS: Fetcher;
  ROOM: DurableObjectNamespace<import('./worker/index').RoomDO>;
  LOBBY: DurableObjectNamespace<import('./worker/index').LobbyDO>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index');
    durableNamespaces: 'RoomDO' | 'LobbyDO';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
